"""Static morphology tables for the word-mesh feature.

Offline layer of P3: prefixes/suffixes/roots with meanings and example
words. The decomposer uses these to break a word into morphemes and to
find its word family (other examples sharing a root). The LLM layer
(synonyms/antonyms) augments this at runtime.
"""

from __future__ import annotations

# (morpheme, meaning-zh, examples)
PREFIXES: list[tuple[str, str, list[str]]] = [
    ("anti", "反对，对抗", ["antibody", "anticlimax", "antidote", "antisocial"]),
    ("auto", "自动，自己", ["automatic", "autobiography", "autonomy"]),
    ("bene", "好，善", ["benefit", "benevolent", "benign"]),
    ("circum", "环绕", ["circumstance", "circumference", "circumnavigate"]),
    ("co", "共同", ["cooperate", "coexist", "coordinate", "coworker"]),
    ("contra", "相反", ["contradict", "contrary", "contrast"]),
    ("counter", "反对，反向", ["counterattack", "counterpart", "counterclockwise"]),
    ("de", "去除，向下", ["decode", "devalue", "descend", "detract"]),
    ("dis", "否定，分离", ["disagree", "disappear", "disconnect", "dishonest"]),
    ("ex", "向外；前任", ["export", "exclude", "exhale", "ex-president"]),
    ("extra", "额外，超出", ["extraordinary", "extracurricular", "extrasensory"]),
    ("fore", "前，预先", ["forecast", "foreshadow", "foresee", "foreword"]),
    ("hyper", "过度，超出", ["hyperactive", "hypertension", "hypercritical"]),
    ("il", "不（同 in-）", ["illegal", "illogical", "illiterate"]),
    ("im", "不；进入", ["impossible", "immature", "import", "imprison"]),
    ("inter", "之间，相互", ["international", "interact", "intervene"]),
    ("intro", "向内", ["introduce", "introspect", "introvert"]),
    ("macro", "大，宏观", ["macroeconomics", "macro", "macroscale"]),
    ("mal", "坏，不良", ["malfunction", "malnutrition", "malice"]),
    ("micro", "微，小", ["microscope", "microwave", "microorganism"]),
    ("mis", "错误", ["misunderstand", "mislead", "misfortune"]),
    ("mono", "单一", ["monopoly", "monologue", "monotone"]),
    ("multi", "多", ["multimedia", "multinational", "multiply"]),
    ("neo", "新", ["neologism", "neoclassical", "neonatal"]),
    ("non", "非，不", ["nonsense", "nonfiction", "nonprofit"]),
    ("ob", "逆，对抗", ["obstacle", "object", "oppose", "obstruct"]),
    ("omni", "全，总", ["omnipresent", "omniscient", "omnivore"]),
    ("over", "过度，在上", ["overcome", "overlook", "overestimate"]),
    ("para", "旁边；辅助", ["parallel", "paramedic", "paradox", "paragraph"]),
    ("peri", "周围", ["perimeter", "period", "periscope"]),
    ("poly", "多", ["polygon", "polyglot", "polynomial"]),
    ("post", "后", ["postpone", "postwar", "postgraduate", "postscript"]),
    ("pre", "前，预先", ["predict", "prevent", "preview", "precede"]),
    ("pro", "向前；支持", ["progress", "proceed", "promote", "pro-American"]),
    ("re", "再次，返回", ["return", "rebuild", "review", "recall"]),
    ("semi", "半", ["semicircle", "semifinal", "semiautomatic"]),
    ("sub", "下，次", ["subway", "submarine", "subtitle", "subordinate"]),
    ("super", "超，上", ["superman", "supervise", "superficial", "superior"]),
    ("sur", "上，超过", ["surface", "surpass", "survive", "surreal"]),
    ("sym", "共同，相同", ["sympathy", "symphony", "symmetry", "synchronize"]),
    ("trans", "跨越，转移", ["transport", "transfer", "translate", "transform"]),
    ("tri", "三", ["triangle", "triple", "tricycle"]),
    ("ultra", "极端，超", ["ultraviolet", "ultrasound", "ultramodern"]),
    ("un", "不，否定", ["unhappy", "unable", "unlock", "unpredictable"]),
    ("under", "下；不足", ["underground", "underestimate", "undergo", "underline"]),
    ("uni", "单一", ["uniform", "universe", "unify", "unicorn"]),
]

# (morpheme, meaning-zh, examples)
SUFFIXES: list[tuple[str, str, list[str]]] = [
    ("able", "可…的", ["readable", "acceptable", "predictable", "portable"]),
    ("acle", "名词后缀", ["miracle", "spectacle", "obstacle"]),
    ("age", "行为/结果（名词）", ["storage", "marriage", "breakage"]),
    ("al", "…的；行为（形/名）", ["natural", "removal", "arrival", "personal"]),
    ("ance", "状态/性质（名词）", ["importance", "resistance", "appearance"]),
    ("ate", "使…（动词）", ["activate", "motivate", "create", "educate"]),
    ("ation", "行为/结果（名词）", ["information", "creation", "observation"]),
    ("cy", "状态/职位（名词）", ["privacy", "accuracy", "democracy", "bureaucracy"]),
    ("dom", "状态/领域（名词）", ["freedom", "kingdom", "wisdom", "boredom"]),
    ("en", "使…（动词）", ["strengthen", "broaden", "shorten", "darken"]),
    ("ence", "状态/性质（名词）", ["difference", "existence", "preference"]),
    ("er", "人/物（名词）", ["teacher", "worker", "container", "printer"]),
    ("ful", "充满…的", ["careful", "helpful", "beautiful", "meaningful"]),
    ("ible", "可…的", ["visible", "flexible", "responsible", "plausible"]),
    ("ic", "…的（形容词）", ["heroic", "academic", "specific", "magnetic"]),
    ("ify", "使…化（动词）", ["simplify", "clarify", "identify", "justify"]),
    ("ish", "略…的；…族的", ["childish", "reddish", "Spanish", "selfish"]),
    ("ism", "主义/学说（名词）", ["realism", "capitalism", "criticism", "optimism"]),
    ("ist", "…的人（名词）", ["artist", "scientist", "optimist", "tourist"]),
    ("ite", "…的；追随者", ["favorite", "polite", "socialite"]),
    ("ity", "性质（名词）", ["ability", "reality", "simplicity", "similarity"]),
    ("ive", "有…性质的", ["active", "creative", "effective", "supportive"]),
    ("ize", "使…化（动词）", ["modernize", "realize", "organize", "recognize"]),
    ("less", "无…的", ["hopeless", "careless", "endless", "priceless"]),
    ("ly", "…地；…的", ["quickly", "happily", "friendly", "daily"]),
    ("ment", "行为/结果（名词）", ["movement", "development", "argument", "judgment"]),
    ("ness", "状态（名词）", ["happiness", "darkness", "kindness", "awareness"]),
    ("ology", "…学（名词）", ["biology", "psychology", "technology", "geology"]),
    ("ous", "多…的", ["dangerous", "famous", "nervous", "generous"]),
    ("ship", "状态/关系（名词）", ["friendship", "leadership", "relationship"]),
    ("tion", "行为/结果（名词）", ["action", "education", "production"]),
    ("ture", "行为/结果（名词）", ["future", "nature", "culture", "picture"]),
    ("ward", "向…（方向）", ["forward", "backward", "toward", "upward"]),
    ("y", "…的；性质（形/名）", ["windy", "healthy", "difficulty", "jealousy"]),
]

# (root, meaning-zh, origin, examples)
ROOTS: list[tuple[str, str, str, list[str]]] = [
    ("aud", "听", "拉丁", ["audio", "audience", "audible", "auditorium"]),
    ("bene", "好", "拉丁", ["benefit", "benefactor", "benevolent"]),
    ("bio", "生命", "希腊", ["biology", "biography", "antibiotic", "symbiosis"]),
    ("chron", "时间", "希腊", ["chronology", "chronic", "synchronize", "anachronism"]),
    ("cid", "落下；切割", "拉丁", ["decide", "suicide", "incident", "coincide"]),
    ("circ", "环，圆", "拉丁", ["circle", "circulate", "circuit", "circumference"]),
    ("claim", "喊，声明", "拉丁", ["exclaim", "proclaim", "declare", "clamor"]),
    ("clud", "关闭", "拉丁", ["include", "exclude", "conclude", "preclude"]),
    ("cogn", "知道", "拉丁", ["recognize", "cognition", "cognitive"]),
    ("cord", "心", "拉丁", ["accord", "concord", "discord", "cordial"]),
    ("corp", "身体", "拉丁", ["corporation", "corpse", "incorporate", "corps"]),
    ("cred", "相信", "拉丁", ["credit", "credible", "incredible", "credential"]),
    ("cur", "跑；关心", "拉丁", ["current", "occur", "curriculum", "secure"]),
    ("dict", "说", "拉丁", ["predict", "dictate", "dictionary", "contradict"]),
    ("duc", "引导", "拉丁", ["educate", "conduct", "produce", "reduce"]),
    ("fac", "做，制作", "拉丁", ["factory", "facilitate", "manufacture", "effect"]),
    ("fer", "带来，携带", "拉丁", ["transfer", "refer", "differ", "offer"]),
    ("flect", "弯曲", "拉丁", ["reflect", "flexible", "deflect", "inflection"]),
    ("flu", "流", "拉丁", ["fluent", "influence", "fluid", "flux"]),
    ("form", "形状", "拉丁", ["reform", "transform", "uniform", "formation"]),
    ("fract", "破裂", "拉丁", ["fracture", "fragment", "fragile", "refraction"]),
    ("fusion", "融合，流", "拉丁", ["confusion", "diffusion", "fusion", "infuse"]),
    ("gen", "出生，产生", "拉丁/希腊", ["generate", "genetic", "generation", "degenerate"]),
    ("geo", "地球", "希腊", ["geography", "geology", "geometry", "geothermal"]),
    ("grad", "步，级", "拉丁", ["gradual", "graduate", "progress", "degrade"]),
    ("graph", "写，画", "希腊", ["photograph", "biography", "geography", "autograph"]),
    ("grav", "重", "拉丁", ["gravity", "grave", "aggravate", "gravid"]),
    ("helio", "太阳", "希腊", ["heliocentric", "helium", "heliosphere"]),
    ("hydr", "水", "希腊", ["hydrogen", "hydrant", "dehydration", "hydraulic"]),
    ("ject", "投掷", "拉丁", ["project", "reject", "inject", "eject"]),
    ("jud", "判断", "拉丁", ["judge", "judgment", "judicial", "prejudice"]),
    ("lect", "选择；读", "拉丁", ["select", "collect", "elect", "lecture"]),
    ("log", "言语，学说", "希腊", ["dialogue", "logic", "apology", "eulogy"]),
    ("loqu", "说话", "拉丁", ["eloquent", "soliloquy", "colloquial"]),
    ("man", "手", "拉丁", ["manual", "manage", "manufacture", "manuscript"]),
    ("mit", "送，放", "拉丁", ["submit", "permit", "transmit", "admit"]),
    ("mort", "死亡", "拉丁", ["mortal", "mortgage", "immortal", "mortality"]),
    ("mov", "移动", "拉丁", ["move", "remove", "movement", "immovable"]),
    ("path", "感情；疾病", "希腊", ["sympathy", "empathy", "apathy", "pathology"]),
    ("ped", "脚", "拉丁/希腊", ["pedal", "pedestrian", "biped", "impede"]),
    ("pel", "推，驱动", "拉丁", ["propel", "expel", "compel", "repel"]),
    ("pend", "悬挂；称量", "拉丁", ["depend", "suspend", "pendant", "append"]),
    ("phon", "声音", "希腊", ["telephone", "symphony", "microphone", "phonetics"]),
    ("photo", "光", "希腊", ["photograph", "photosynthesis", "photon"]),
    ("pon", "放置", "拉丁", ["postpone", "component", "opponent", "compound"]),
    ("port", "搬运", "拉丁", ["transport", "import", "export", "portable"]),
    ("pos", "放置", "拉丁", ["position", "compose", "deposit", "expose"]),
    ("press", "压", "拉丁", ["compress", "express", "impress", "depress"]),
    ("quer", "寻求；问", "拉丁", ["query", "question", "inquire", "require"]),
    ("rupt", "破裂", "拉丁", ["interrupt", "rupture", "erupt", "bankrupt"]),
    ("scrib", "写", "拉丁", ["describe", "subscribe", "scribble", "inscribe"]),
    ("sect", "切割", "拉丁", ["section", "intersect", "dissect", "sector"]),
    ("spec", "看", "拉丁", ["inspect", "respect", "spectator", "perspective"]),
    ("struct", "建造", "拉丁", ["structure", "construct", "instruct", "destroy"]),
    ("tact", "接触", "拉丁", ["contact", "tactile", "intact", "tangent"]),
    ("tele", "远", "希腊", ["telephone", "television", "telegraph", "telescope"]),
    ("temp", "时间", "拉丁", ["temporary", "contemporary", "tempo"]),
    ("term", "边界，末端", "拉丁", ["terminal", "determine", "terminate", "exterminate"]),
    ("tract", "拉，拖", "拉丁", ["attract", "extract", "contract", "distract"]),
    ("ven", "来", "拉丁", ["event", "invent", "prevent", "convene"]),
    ("vert", "转", "拉丁", ["convert", "reverse", "divert", "introvert"]),
    ("vid", "看", "拉丁", ["video", "evident", "provide", "envision"]),
    ("vis", "看", "拉丁", ["visible", "vision", "visual", "revise"]),
    ("voc", "声音，喊", "拉丁", ["vocal", "vocabulary", "advocate", "provoke"]),
    ("vol", "意愿；转", "拉丁", ["voluntary", "volition", "revolution"]),
]
