"""Built-in scenario expression bank (场景表达种子库).

Curated business/academic/daily collocations with Chinese glosses.
Seeded content keeps scenario search useful without any LLM call;
an LLM expansion pass can extend this later through the same index.
"""

from __future__ import annotations

SCENES: dict[str, str] = {
    "business_email": "商务邮件",
    "academic": "学术写作",
    "daily": "日常口语",
}

# (scene, en, zh, note)
ENTRIES: list[tuple[str, str, str, str]] = [
    # ---------- business email ----------
    ("business_email", "I am writing to follow up on", "我写信是想跟进……",
     "邮件开头点明来意的标准句式"),
    ("business_email", "Please find attached", "请查收附件",
     "随附件发送信息的地道说法，避免中式 'please check the attachment'"),
    ("business_email", "Touch base", "简短沟通对齐一下",
     "口语化商务用语：快速同步进展"),
    ("business_email", "Circle back", "稍后再回头讨论",
     "会议中暂置话题、之后再谈"),
    ("business_email", "At your earliest convenience", "在您方便时尽早",
     "比 as soon as possible 更礼貌的催促"),
    ("business_email", "Per our conversation", "如我们此前所谈",
     "引用此前沟通内容的正式开头"),
    ("business_email", "Moving forward", "接下来/今后",
     "商务语境中指后续安排，比 in the future 更地道"),
    ("business_email", "Get the ball rolling", "推动启动",
     "让事情开始运转的口语化表达"),
    ("business_email", "On the same page", "达成一致/信息同步",
     "确认双方理解一致"),
    ("business_email", "Reach a consensus", "达成共识",
     "正式表达：形成一致意见"),
    ("business_email", "Bear with us", "请稍候/请耐心等待",
     "请求对方等待的礼貌说法"),
    ("business_email", "Without further ado", "不再赘述",
     "进入正题前的过渡语"),
    ("business_email", "It slipped my mind", "我一时忘记了",
     "承认疏忽的自然表达，比 I forgot 更委婉"),
    ("business_email", "Take it offline", "会后单独再聊",
     "会议中把话题移出全体讨论"),
    ("business_email", "Action item", "待办事项/行动项",
     "会议纪要标准用词"),
    ("business_email", "Close of business (COB)", "下班前/当日截止",
     "商务截止时间惯用缩写"),
    ("business_email", "Kindly note that", "请知悉",
     "提示重点信息的正式引导语"),
    ("business_email", "We regret to inform you", "很遗憾地通知您",
     "拒绝/坏消息的正式开头"),
    ("business_email", "Thank you in advance", "先谢谢您了",
     "预致谢意（部分语境可能显得理所当然，慎用）"),
    ("business_email", "Attached please find", "附件中请查收",
     "较老派但正式的附件表达"),
    ("business_email", "Look forward to hearing from you", "期待您的回复",
     "邮件结尾惯用语"),
    ("business_email", "Should you have any questions", "如有任何疑问",
     "结尾引导提问的标准句式"),
    ("business_email", "Due diligence", "尽职调查/审慎核实",
     "交易、合作前的核查流程"),
    ("business_email", "Win-win situation", "双赢局面",
     "商务谈判常用"),
    ("business_email", " ballpark figure", "大致数字/粗略估计",
     "报价前先给个大致范围"),
    ("business_email", "Bandwidth", "精力/处理能力",
     "口语化：有没有余力接手新任务"),
    ("business_email", "Leverage our strengths", "发挥我们的优势",
     "leverage 在商务英语中比 use 更常见"),
    ("business_email", "Streamline the process", "精简流程",
     "优化效率的标准搭配"),
    ("business_email", "Best regards", "顺颂商祺",
     "邮件落款：正式而友好"),
    ("business_email", "Deadline is fast approaching", "截止日期临近",
     "提醒时限的常用句"),

    # ---------- academic writing ----------
    ("academic", "This paper argues that", "本文主张……",
     "论文陈述核心论点的标准句式"),
    ("academic", "To the best of our knowledge", "据我们所知",
     "强调首创性的限定表达"),
    ("academic", "A growing body of literature", "越来越多的文献",
     "文献综述中描述研究趋势"),
    ("academic", "remains understudied", "仍缺乏研究",
     "指出研究空白（research gap）"),
    ("academic", "sheds light on", "阐明/揭示",
     "说明研究贡献的高频搭配"),
    ("academic", "paves the way for", "为……铺平道路",
     "指出研究意义与后续方向"),
    ("academic", "In light of these findings", "基于这些发现",
     "讨论部分承接结果"),
    ("academic", "Contrary to previous research", "与既往研究相反",
     "呈现对比性发现"),
    ("academic", "Taken together, these results suggest", "综合来看，这些结果表明",
     "汇总多项结果的标准句式"),
    ("academic", "with respect to", "关于/就……而言",
     "比 about 更正式的学术表达"),
    ("academic", "plays a pivotal role in", "在……中起关键作用",
     "描述作用与重要性"),
    ("academic", "a double-edged sword", "双刃剑",
     "描述利弊并存的现象"),
    ("academic", "the underlying mechanism", "潜在机制",
     "解释现象背后的原理"),
    ("academic", "empirical evidence", "实证证据",
     "基于观察与数据的研究证据"),
    ("academic", "statistically significant", "统计学显著",
     "统计结果描述的固定搭配"),
    ("academic", "correlates positively with", "与……正相关",
     "描述变量关系"),
    ("academic", "account for", "解释/占比",
     "学术双义高频动词：解释原因或说明比例"),
    ("academic", "give rise to", "引起/导致",
     "比 cause 更书面的因果表达"),
    ("academic", "It is worth noting that", "值得注意的是",
     "强调要点的高频学术句式"),
    ("academic", "further investigation is warranted", "值得进一步研究",
     " limitations 部分指出后续方向的标准说法"),
    ("academic", "bolster the argument", "支撑论点",
     "bolster 比 support 更有力"),
    ("academic", "a caveat is in order", "需要说明一点保留意见",
     "提出限制条件的正式方式"),
    ("academic", "draws on", "借鉴/基于",
     "说明方法论来源"),
    ("academic", "insofar as", "在……范围内",
     "精确限定条件的高级连接词"),
    ("academic", "By and large", "总体而言",
     "概括总体趋势的口语化学术表达"),
    ("academic", "a subset of", "……的一个子集",
     "描述样本与集合关系"),
    ("academic", "align with the hypothesis", "与假设一致",
     "结果验证假设的标准表达"),
    ("academic", "Nuanced understanding", "细致入微的理解",
     "强调分析深度"),
    ("academic", "complement rather than replace", "是补充而非替代",
     "讨论人机/AI 关系等话题的高频句式"),
    ("academic", "yields conflicting results", "产生了相互矛盾的结果",
     "文献综述描述争议"),

    # ---------- daily conversation ----------
    ("daily", "Long story short", "长话短说",
     "快速给出结论的口语引导"),
    ("daily", "I'm all ears", "我洗耳恭听",
     "表示感兴趣、愿意倾听"),
    ("daily", "Speak of the devil", "说曹操曹操到",
     "谈到某人时其恰好出现"),
    ("daily", "It's up to you", "由你决定",
     "把选择权交给对方"),
    ("daily", "No worries", "没关系/不用谢",
     "回应感谢或道歉的万能口语"),
    ("daily", "I'm beat", "我累垮了",
     "表达极度疲惫的口语"),
    ("daily", "Grab a bite", "随便吃点东西",
     "非正式用餐说法"),
    ("daily", "My treat", "我请客",
     "主动买单的地道说法"),
    ("daily", "Sleep on it", "考虑一晚再决定",
     "推迟决定、慎重思考"),
    ("daily", "Under the weather", "身体不舒服",
     "委婉表示生病的口语"),
    ("daily", "Piece of cake", "小菜一碟",
     "形容事情非常容易"),
    ("daily", "Cost an arm and a leg", "贵得离谱",
     "形容价格极高"),
    ("daily", "Once in a blue moon", "千载难逢/极少发生",
     "形容稀有事件"),
    ("daily", "Hit the books", "用功读书",
     "学习备考的口语表达"),
    ("daily", "Call it a day", "今天就到这吧",
     "结束工作/活动的说法"),
    ("daily", "Spill the beans", "泄露秘密",
     "不小心或故意说漏"),
    ("daily", "Break the ice", "打破僵局/破冰",
     "社交场合开启话题"),
    ("daily", "Bite the bullet", "硬着头皮做",
     "面对不情愿的事硬撑过去"),
    ("daily", "Wrap one's head around", "理解/消化（复杂事物）",
     "努力弄懂某事"),
    ("daily", "Off the top of my head", "凭印象/不假思索",
     "未查证的情况下随口说"),
    ("daily", "Go with the flow", "随大流/顺其自然",
     "不刻意强求"),
    ("daily", "Cut to the chase", "直入主题",
     "要求对方别绕弯子"),
    ("daily", "Throw someone under the bus", "甩锅/牺牲某人",
     "为自保出卖他人"),
    ("daily", "The ball is in your court", "该你做决定了",
     "把责任交给对方"),
    ("daily", "Raining cats and dogs", "倾盆大雨",
     "经典口语比喻"),
    ("daily", "Beat around the bush", "拐弯抹角",
     "不直接说重点"),
    ("daily", "Get cold feet", "临阵退缩",
     "事到临头突然不敢了"),
    ("daily", "On cloud nine", "欣喜若狂",
     "形容极度开心"),
    ("daily", "Pull an all-nighter", "通宵熬夜",
     "学生党常用：熬夜赶工"),
    ("daily", "Play it by ear", "见机行事",
     "不预先计划、随机应变"),
]
